vms:
  - name: web-01
    tenant: test
    hypervisor: proxmox
    boot_method: iso       # iso | image | pxe
    cpus: 4
    memory_mb: 16384
    disks:
      - size_gb: 40
        storage: local-lvm
        type: scsi
    netifs:
      - bridge: vmbr0
        model: virtio
    proxmox:
      node: fkarcsi
      storage: local-lvm
      iso_storage: local

  - name: ci-runner-01
    hypervisor: proxmox
    boot_method: image
    cpus: 4
    memory_mb: 8192
    disks:
      - size_gb: 60
        storage: local-lvm
        type: scsi
    netifs:
      - bridge: vmbr0
        vlan: 20
        model: virtio
    proxmox:
      node: fkarcsi
      storage: local-lvm

  - name: baremetal-01
    hypervisor: baremetal
    boot_method: pxe
    cpus: 8
    memory_mb: 16384
    disks:
      - size_gb: 200
        storage: "n/a"
        type: scsi
    netifs:
      - bridge: "eno1"
        vlan: null
        mac: "52:54:00:aa:bb:cc"


  - name: nixos-vm-01  # This is your new NixOS VM
    hypervisor: proxmox
    cpus: 4
    memory_mb: 16384
    disks:
      - size_gb: 100
        storage: local-lvm # Your Proxmox storage
    netifs:
      - bridge: vmbr0     # Your Proxmox bridge
    proxmox:
      node: fkarcsi         # Your Proxmox node name