# sops configuration file
# Defines encryption keys and rules for secret management

creation_rules:
  # Apply to all .yaml files in this directory
  - path_regex: secrets\.yaml$
    # Encrypt specific fields (everything under 'data')
    encrypted_regex: "^(data|stringData|.*[Pp]assword.*|.*[Ss]ecret.*|.*[Tt]oken.*)$"

    # Age encryption keys
    # Add your age public key here (generate with: age-keygen)
    key_groups:
      - age:
          # IMPORTANT: Replace with your actual age public key
          # Generate with: age-keygen -o ~/.config/sops/age/keys.txt
          # Public key format: age1...
          - &admin_key age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p

    # Additional keys for team members can be added here
    # - age:
    #     - age1... # Team member 1
    #     - age1... # Team member 2
