# WSL with static IP (flat style, as you sent)
- name: wsl
  username: wsluser
  mode: static
  interface: eth0
  ipv4: { address: 192.168.1.60, prefixLength: 24, gateway: 192.168.1.1, nameservers: [8.8.8.8, 1.1.1.1] }

# New DHCP host (nested style)
- name: wsl_dhcp
  username: wsluser_dhcp
  net:
    mode: dhcp
    interface: eth0
