# Do not modify this file!  It was generated by 'nixos-generate-config'
# on the target machine and may be overwritten by future invocations.
# Please make changes to default.nix instead.
{ config, lib, pkgs, modulesPath,... }:
{
  imports = [];

  # This file will be populated with hardware-specific settings
  # after running `nixos-generate-config --root /mnt` on the target server.
  # For now, it remains a placeholder.
}